import { PlayerColor, UnitType } from 'common/unit';

export const UnitSprites = {
    [PlayerColor.NEUTRAL]: {
        [UnitType.CITY]: 8,
        [UnitType.INFANTRY]: 106,
        [UnitType.HQ]: 9,
        [UnitType.FACTORY]: 11,
        [UnitType.AIRPORT]: 15,
        [UnitType.DOCK]: 12,
        [UnitType.TANK]: 0,
        [UnitType.SHIP]: 0,
        [UnitType.JET]: 0,
        [UnitType.HELICOPTER]: 0,
        [UnitType.TRANSPORT]: 0,
        [UnitType.APC]: 0,
        [UnitType.ANTI_TANK]: 0,
        [UnitType.LANDER]: 0,
        [UnitType.ROCKET_TRUCK]: 0,
    },
    [PlayerColor.RED]: {
        [UnitType.CITY]: 62,
        [UnitType.INFANTRY]: 160,
        [UnitType.HQ]: 63,
        [UnitType.FACTORY]: 65,
        [UnitType.AIRPORT]: 69,
        [UnitType.DOCK]: 66,
        [UnitType.TANK]: 152,
        [UnitType.SHIP]: 158,
        [UnitType.JET]: 154,
        [UnitType.HELICOPTER]: 155,
        [UnitType.TRANSPORT]: 156,
        [UnitType.APC]: 150,
        [UnitType.ANTI_TANK]: 161,
        [UnitType.LANDER]: 157,
        [UnitType.ROCKET_TRUCK]: 153,
    },
    [PlayerColor.BLUE]: {
        [UnitType.CITY]: 44,
        [UnitType.INFANTRY]: 142,
        [UnitType.HQ]: 45,
        [UnitType.FACTORY]: 47,
        [UnitType.AIRPORT]: 51,
        [UnitType.DOCK]: 48,
        [UnitType.TANK]: 134,
        [UnitType.SHIP]: 140,
        [UnitType.JET]: 136,
        [UnitType.HELICOPTER]: 137,
        [UnitType.TRANSPORT]: 138,
        [UnitType.APC]: 132,
        [UnitType.ANTI_TANK]: 143,
        [UnitType.LANDER]: 139,
        [UnitType.ROCKET_TRUCK]: 135,
    },
    [PlayerColor.GREEN]: {
        [UnitType.CITY]: 26,
        [UnitType.INFANTRY]: 124,
        [UnitType.HQ]: 27,
        [UnitType.FACTORY]: 29,
        [UnitType.AIRPORT]: 33,
        [UnitType.DOCK]: 30,
        [UnitType.TANK]: 116,
        [UnitType.SHIP]: 122,
        [UnitType.JET]: 118,
        [UnitType.HELICOPTER]: 119,
        [UnitType.TRANSPORT]: 120,
        [UnitType.APC]: 114,
        [UnitType.ANTI_TANK]: 125,
        [UnitType.LANDER]: 121,
        [UnitType.ROCKET_TRUCK]: 117,
    },
    [PlayerColor.YELLOW]: {
        [UnitType.CITY]: 80,
        [UnitType.INFANTRY]: 178,
        [UnitType.HQ]: 81,
        [UnitType.FACTORY]: 83,
        [UnitType.AIRPORT]: 87,
        [UnitType.DOCK]: 84,
        [UnitType.TANK]: 170,
        [UnitType.SHIP]: 176,
        [UnitType.JET]: 172,
        [UnitType.HELICOPTER]: 173,
        [UnitType.TRANSPORT]: 174,
        [UnitType.APC]: 168,
        [UnitType.ANTI_TANK]: 179,
        [UnitType.LANDER]: 175,
        [UnitType.ROCKET_TRUCK]: 171,
    },
}